# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: true
security.basic.enabled: false

# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false

# security configuration (this key should be unique for your application, and kept secret)
jhipster.security.rememberme.key: 01a1011a2082773f0f8f7b5bcf60d3253f117c41

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

mail:
    host: localhost
    port: 25
    username: root
    password: RootPortNr.3306
    protocol: smtp
    tls: false
    auth: false
    from: rentAVehicle@localhost


swagger:
    title: rentAVehicle API
    description: rentAVehicle applications and beyond!
    termsOfServiceUrl: http://jhipster.github.io/
    contact:
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
